### ISSUE TITLE
Any further updates?

### ISSUE THREAD

**Issue by rahulkhatri137** [aNNiMON/tgbots-module#9]

**Comment by aNNiMON** [comment]
@rahulkhatri137, yes, but currently I'm unable to do this due to situation in Ukraine.  Once I return to my home, I'll continue to work on this library. 😸 

If you want to use a bit updated version of telegram bots API, I suggest to force update a parent library in your build.gradle:

```java
implementation('com.annimon:tgbots-module:5.7.0') {
    exclude group: 'org.telegram', module: 'telegrambots'
}
implementation 'org.telegram:telegrambots:6.1.0'
````

This fixes the file_size problem if premium users send 4GB document to your bot.
